server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/notificationdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.namnd.kafka.events.envelope.EventEnvelope
        spring.json.trusted.packages: com.namnd.kafka.events.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:nghiemducnam0312@gmail.com}
    password: ${MAIL_PASSWORD:sdxm fmia vuzf bvmq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  auth:
    secret: ${JWT_SECRET:kBJb8FEOvTCWEcfZB6RLMM5BLoI8p0FWOWEu7FSZBYn+ItVi7mHRePYCvum5Ic6l4M2nFw+kdl8du99Bxnb7zg==}
    public-paths:
      - /actuator/health
      - /actuator/prometheus
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /api/notifications/stream

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}  # Use 0.1 or lower in production
  otlp:
    tracing:
      endpoint: http://${OTEL_COLLECTOR_HOST:localhost}:4318/v1/traces
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      deployment.environment: ${DEPLOYMENT_ENV:dev}
